specVersion: 0.2.0
name: acala-dex
version: 1.0.0
description: ''
repository: ''
schema:
  file: ./schema.graphql
network:
  genesisHash: '0xfc41b9bd8ef8fe53d58c7ea67c794c7ec9a73daf05e6d54b14ff6342c99ba64c'
  endpoint: wss://acala-fullnode-01.bdnodes.net:8443/parachain?auth=fmxRFPt9l5OB5Yu42TOmdT25VTSKr0ixx5YDzgrN1n0
  dictionary: https://api.subquery.network/sq/subquery/acala-dictionary
  chaintypes:
    file: './src/chain-types.js'
dataSources:
  - kind: substrate/Runtime
    startBlock: 1
    mapping:
      file: "./dist/index.js"
      handlers:
        - handler: handleProvisioningToEnabled
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ProvisioningToEnabled
        - handler: handleAddLiquidity
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddLiquidity
        - handler: handleRemoveLiquidity
          kind: substrate/EventHandler
          filter:
            module: dex
            method: RemoveLiquidity
        - handler: handleSwap
          kind: substrate/EventHandler
          filter:
            module: dex
            method: Swap
        - handler: handleListProvision
          kind: substrate/EventHandler
          filter:
            module: dex
            method: ListProvisioning
        - handler: handleAddProvision
          kind: substrate/EventHandler
          filter:
            module: dex
            method: AddProvision